# Generated by Django 5.2.4 on 2025-09-11 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('prize', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('miscellaneous_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('waiting', 'Waiting')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_tokens', to='giveaways.giveaway')),
            ],
        ),
        migrations.CreateModel(
            name='GiveawayWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('x_username', models.CharField(max_length=255)),
                ('giveaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winners', to='giveaways.giveaway')),
            ],
        ),
    ]
