# Generated by Django 5.2.4 on 2025-07-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitlist',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
